# One-time setup configuration for this template
# Edit the values below, then run the setup script to apply changes.

# Distribution/project name (PyPI/repo name), e.g., my-package
distribution_name: kodachrome

# Python package import name (directory name), e.g., my_package
import_name: kchrome

# Short description of the package
description: K-Scale Open Deployment Automation and Control Hub for Ranking, Organization, Management and Evaluation.

# Project URL (e.g., repository URL)
url: https://github.com/kscalelabs/kodachrome

# Author identity
author: alik-git
author_email: ali@kscale.dev

# Minimum supported Python version (string)
python_min_version: "3.11"

# Initial package version (string set in <import_name>/__init__.py)
version: "0.0.1"

# Default branch for CI triggers (use "master" or "main")
default_branch: master

# Year for LICENSE
year: 2025 